apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-sentinel

resources:
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: kube-sentinel
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/managed-by: kustomize

images:
  - name: ghcr.io/kube-sentinel/kube-sentinel
    newTag: latest
